name: Build, migrate & deploy ASP.Net Core to Azure Web App - bayacommerce

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore ECommerce.csproj --no-cache

      - name: Clean previous build
        run: dotnet clean ECommerce.csproj

      - name: Build project
        run: dotnet build ECommerce.csproj --configuration Release --no-restore

      - name: Publish project (framework-dependent)
        run: dotnet publish ECommerce.csproj -c Release -o ./publish --no-build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ./publish

  migrate:
    runs-on: windows-latest
    needs: build
    # On n'a pas besoin d'Azure Login ici : on migre via la chaîne de connexion
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore EF Core tool (si vous utilisez un manifest local)
        run: dotnet tool restore

      - name: Apply EF Core migrations
        # On fournit la chaîne de connexion Azure SQL depuis GitHub Secrets
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION }}
          DOTNET_ENVIRONMENT: Production
        run: |
          dotnet ef database update \
            --project ECommerce.csproj \
            --startup-project ECommerce.csproj \
            --configuration Release

  deploy:
    runs-on: windows-latest
    needs: [build, migrate]
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: net-app
          path: ./net-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name:   'bayacommerce'
          slot-name:  'Production'
          package:    ./net-app

      - name: Show deployed URL
        run: echo "https://${{ secrets.AZURE_APP_NAME }}.azurewebsites.net"
