name: Build and deploy ASP.Net Core app to Azure Web App - bayacommerce

on:
  push:
    branches:
      - main  # Détecte automatiquement les pushs sur la branche principale
  workflow_dispatch:  # Permet également d'exécuter le workflow manuellement si nécessaire

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Permet de récupérer le code depuis le dépôt

    steps:
      - uses: actions/checkout@v4  # Récupère le code depuis le dépôt GitHub

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'  # Spécifie la version de .NET Core à utiliser

      - name: Build with dotnet
        run: dotnet build ECommerce.csproj --configuration Release  # Compilation du projet

      - name: dotnet publish
        run: dotnet publish ECommerce.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"  # Publication explicite du projet

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp  # Charge l'artefact généré pour le job de déploiement

  deploy:
    runs-on: windows-latest
    needs: build  # Dépend du job 'build'
    environment:
      name: 'Production'  # Le nom de l'environnement de déploiement
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  # URL de l'App Service après le déploiement
    permissions:
      id-token: write  # Nécessaire pour la demande de jeton JWT
      contents: read  # Nécessaire pour récupérer le code

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app  # Télécharge l'artefact du job de construction

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ADD88DF0C6384746AAD2B8F8A730192C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_24746A3ADB3B408297626E1859585E56 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_048FC10734D44A38BE50F905CCCD2470 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bayacommerce'
          slot-name: 'Production'
          package: .net-app  # On utilise l'artefact téléchargé pour le déploiement
